# Generated by Django 2.2 on 2019-04-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendsnaps', '0002_drinkevent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
