# Generated by Django 2.2 on 2019-04-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendsnaps', '0003_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkevent',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
