# Generated by Django 2.2 on 2019-04-06 21:41

import backendsnaps.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendsnaps', '0004_auto_20190406_0821'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', backendsnaps.models.CustomUserManager()),
            ],
        ),
    ]
