version: "3"

services:
  app:
    build: .
    restart: always
    networks:
      - web
      - default
    volumes:
      - ./.env:/app/.env
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api.snaps.dropud.nu"
      - "traefik.frontend.rule=Host:api.snaps.dropud.nu"
      - "traefik.port=8000"
      - "traefik.docker.network=web"
      - "traefik.domain=api.snaps.dropud.nu"
    container_name: api.snaps.dropud.nu
    depends_on:
      - db

  db:
    image: postgres:12

networks:
  web:
    external: true
