version: "3.7"

services:
  app:
    build: .
    restart: always
    networks:
      - traefik
      - default
    volumes:
      - ./.env:/app/.env
    expose:
      - 8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-snaps-dropud-nu.rule=Host(`api.snaps.dropud.nu`)
      - traefik.http.routers.api-snaps-dropud-nu.tls.certResolver=le
      - traefik.http.services.api-snaps-dropud-nu.loadbalancer.server.port=8000
    container_name: api.snaps.dropud.nu
    depends_on:
      - db

  db:
    image: postgres:12
    volumes:
      - ./db_data:/var/lib/postgresql/data

networks:
  traefik:
    external: true
