version: "3.7"

services:
  app:
    image: api-snaps-dropud-nu
    networks:
      - traefik
      - default
    volumes:
      - ./.env:/app/.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-snaps-dropud-nu.rule=Host(`api.snaps.dropud.nu`)
      - traefik.http.services.api-snaps-dropud-nu.loadbalancer.server.port=8000
    depends_on:
      - db

  db:
    image: postgres:12
    volumes:
      - ./db_data:/var/lib/postgresql/data

networks:
  traefik:
    external: true
